name: C/C++ CI

on:
  create:
    tags:
      - '*'

jobs:
  build_release:
    name: Publish for ${{ matrix.os }}-${{matrix.arch}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: bin/bossac
            asset_name: qbossac
            arch: amd64
            suffix: -linux-amd64
            archive_ext: .tar.bz2
          - os: ubuntu-22.04
            artifact_name: bin/bossac
            asset_name: qbossac
            arch: i686
            suffix: -linux-i686
            make_flags: "EXTRA_FLAGS=-m32"
            archive_ext: .tar.bz2
          - os: windows-latest
            artifact_name: bin/bossac
            asset_name: qbossac
            arch: i686
            msystem: MINGW32
            suffix: -win32
            ext: .exe
            archive_ext: .zip
          - os: windows-latest
            artifact_name: bin/bossac
            asset_name: qbossac
            arch: x86_64
            msystem: MINGW64
            suffix: -win64
            archive_ext: .zip
            ext: .exe
          - os: macos-13
            artifact_name: bin/bossac
            asset_name: qbossac
            arch: amd64
            suffix: -mac
            archive_ext: .tar.bz2

    steps:
    - uses: actions/checkout@v4

    - name: Get tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      shell: bash

    - name: get linux multilib
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: sudo apt-get update; sudo apt-get install gcc-multilib g++-multilib

    - name: get msys2
      uses: msys2/setup-msys2@v2
      if: ${{matrix.os == 'windows-latest'}}
      with:
          msystem: ${{ matrix.msystem }}
          install: git zip base-devel binutils mingw-w64-${{ matrix.arch }}-toolchain
          release: false

    - name: make (win)
      if: ${{matrix.os == 'windows-latest'}}
      shell: msys2 {0}
      run: |
            git reset --hard
            make bossac
            mkdir qbossa-${{ steps.tag.outputs.tag }}
            cp bin/bossac.exe qbossa-${{ steps.tag.outputs.tag }}/qbossac.exe
            zip bin/bossac.zip qbossa-${{ steps.tag.outputs.tag }}/*
            ls qbossa-${{ steps.tag.outputs.tag }}

    - name: make (not win)
      if: ${{matrix.os != 'windows-latest'}}
      run: |
          make bossac ${{matrix.make_flags}}
          mkdir qbossa-${{ steps.tag.outputs.tag }}
          cp bin/bossac qbossa-${{ steps.tag.outputs.tag }}/qbossac
          tar -cjf bin/bossac.tar.bz2 qbossa-${{ steps.tag.outputs.tag }}
          ls qbossa-${{ steps.tag.outputs.tag }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body: "Release ${{ steps.tag.outputs.tag }} of qNimble version of BOSSA"
          files: |
            ${{matrix.artifact_name}}${{matrix.ext}}
            ${{matrix.artifact_name}}${{matrix.archive_ext}}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
