name: C/C++ CI

on:
  create:
    tags:
      - '*'

jobs:
  build_release:
    name: Publish for ${{ matrix.os }}-${{matrix.arch}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            asset_name: qbossac
            arch: amd64
            suffix: -linux-amd64
            archive_ext: .tar.bz2
          - os: ubuntu-22.04
            asset_name: qbossac
            arch: i686
            suffix: -linux-i686
            make_flags: "EXTRA_FLAGS=-m32"
            archive_ext: .tar.bz2
          - os: windows-latest
            asset_name: qbossac
            arch: i686
            msystem: MINGW32
            suffix: -win32
            ext: .exe
            archive_ext: .zip
          - os: windows-latest
            asset_name: qbossac
            arch: x86_64
            msystem: MINGW64
            suffix: -win64
            archive_ext: .zip
            ext: .exe
          - os: macos-14
            asset_name: qbossac
            arch: universal
            suffix: -mac-universal
            make_flags: "EXTRA_FLAGS='-arch arm64'"
            archive_ext: .tar.bz2

    steps:
    - uses: actions/checkout@v6

    - name: Get tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      shell: bash

    - name: get linux multilib
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: sudo apt-get update; sudo apt-get install gcc-multilib g++-multilib

    - name: install mingw (win)
      uses: egor-tensin/setup-mingw@v3
      if: ${{startsWith(matrix.os, 'windows')}}
      with:
          platform: ${{ matrix.arch }}
          version: 14.2.0

    - name: install make and zip (win)
      if: ${{startsWith(matrix.os, 'windows')}}
      run: choco install make zip --no-progress -y
      shell: pwsh

    - name: make (win)
      if: ${{startsWith(matrix.os, 'windows')}}
      shell: bash
      run: |
            g++ --version
            make bossac OS=WIN
            mkdir -p staging/qbossa-${{ steps.tag.outputs.tag }}
            cp bin/bossac.exe staging/qbossa-${{ steps.tag.outputs.tag }}/qbossac.exe
            cp bin/bossac.exe staging/${{matrix.asset_name}}-${{ steps.tag.outputs.tag }}${{matrix.suffix}}${{matrix.ext}}
            cd staging && zip ${{matrix.asset_name}}-${{ steps.tag.outputs.tag }}${{matrix.suffix}}${{matrix.archive_ext}} qbossa-${{ steps.tag.outputs.tag }}/qbossac.exe

    - name: make (not win)
      if: ${{matrix.os != 'windows-latest'}}
      run: |
          g++ --version
          make bossac ${{matrix.make_flags}}
          mkdir -p staging/qbossa-${{ steps.tag.outputs.tag }}
          cp bin/bossac staging/qbossa-${{ steps.tag.outputs.tag }}/qbossac
          tar -cjf staging/${{matrix.asset_name}}-${{ steps.tag.outputs.tag }}${{matrix.suffix}}${{matrix.archive_ext}} -C staging qbossa-${{ steps.tag.outputs.tag }}/qbossac
          cp bin/bossac staging/${{matrix.asset_name}}-${{ steps.tag.outputs.tag }}${{matrix.suffix}}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v3
      with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body: "Release ${{ steps.tag.outputs.tag }} of qNimble version of BOSSA"
          files: staging/*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
