name: C/C++ CI

on:
  create:
    tags:
      - '*'
jobs:    
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{env.GITHUB_REF_SLUG}}
          body: "Release ${{env.GITHUB_REF_SLUG}} of qNimble verion of BOSSA"


  build_release:
    name: Publish for ${{ matrix.os }}-${{matrix.arch}}
    runs-on: ${{ matrix.os }}
    needs: create_release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: bin/bossac
            asset_name: qbossa
            arch: amd64
            suffix: -linux-amd64
          - os: ubuntu-latest
            artifact_name: bin/bossac
            asset_name: qbossa
            arch: i686
            suffix: -linux-i686
            make_flags: "EXTRA_FLAGS=-m32"
          - os: windows-latest
            artifact_name: bin/bossac.exe
            asset_name: qbossa
            arch: i686
            msystem: MINGW32
            suffix: -win32.exe
          - os: windows-latest
            artifact_name: bin/bossac.exe
            asset_name: qbossa
            arch: x86_64
            msystem: MINGW64
            suffix: -win64.exe
          - os: macos-latest
            artifact_name: bin/bossac
            asset_name: qbossa
            arch: amd64
            suffix: -mac

    steps:      
    - uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x            
    - name: get linux multilib
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: sudo apt-get update; sudo apt-get install gcc-multilib g++-multilib
    - name: get msys2
      uses: msys2/setup-msys2@v2
      if: ${{matrix.os == 'windows-latest'}}
      with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel binutils mingw-w64-${{ matrix.arch }}-toolchain
          release: false
    - name: make (win)
      if: ${{matrix.os == 'windows-latest'}}
      shell: msys2 {0}
      run:  |
            git reset --hard
            make bossac
    - name: make (not win)
      if: ${{matrix.os != 'windows-latest'}}
      run: |
          make -n bossac ${{matrix.make_flags}}
          make bossac ${{matrix.make_flags}}
    - name: Upload file
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{matrix.artifact_name}}
          asset_name: ${{matrix.asset_name}}-${{env.GITHUB_REF_SLUG}}${{matrix.suffix}}
          #asset_label: ${{matrix.os}}-${{matrix.arch}}
          asset_content_type: application/octet-stream
